<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "userbatch"
 *
 * Auto generated by Extension Builder 2016-10-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TYPO3 user batch create',
	'description' => 'Backend- and Frontend-User Batch Create from CSV-File',
	'category' => 'module',
	'author' => 'Joe Schäfer',
	'author_email' => 'joe@joekola.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
    // todo: Dokumentaion
);
