<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "userbatch"
 *
 * Auto generated by Extension Builder 2016-10-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Backenduser Batch Create',
	'description' => 'Creates BE User from CSV-File',
	'category' => 'module',
	'author' => 'Joe Schäfer',
	'author_email' => 'schaefer@scw.info',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.9',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
